apiVersion: v1
kind: Secret
metadata:
  name: tekton-basic-user-pass-harbor
  annotations:
    tekton.dev/docker-0: https://core.harbor.domain
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: ******
